#!/usr/bin/with-contenv bash

echo 'export XDG_DATA_DIRS="$XDG_DATA_DIRS:/var/lib/flatpak/exports/share:/config/.local/share/flatpak/exports/share"' >> /etc/skel/.bashrc
echo "xdg-user-dirs-update" >> /etc/skel/.bashrc
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
